name: learn-github-actions
on: [push]
jobs:
  style-check:
    name: Check style with python black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
  test:
    name: Run tests while also collecting coverage information via pytest and the coverage package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with coverage
        run: |
          coverage run -m pytest
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-files
          path: .coverage
          retention-days: 1
          include-hidden-files: true
  coverage-report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install coverage
        run: |
          python -m pip install --upgrade pip
          pip install coverage
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-files
      - name: Generate coverage report
        run: |
          coverage report
          coverage xml
      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 14
